/* ================================================================
   GestionPro — config.js
   Constantes globales : version, Supabase, plans, couleurs
   Chargé en PREMIER avant tous les autres scripts
================================================================ */

/* ── Fonction critique — disponible immédiatement ── */
function escapeHTML(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}



// ─── VERSION : change ce numéro pour vider le cache localStorage automatiquement ───
const GP_APP_VERSION = '3.5.0';
(function() {
  const stored = localStorage.getItem('gp_app_version');
  if (stored !== GP_APP_VERSION) {
    // Nouvelle version → vider les configs qui pourraient être corrompues
    // gp_roles_config géré en Supabase
    localStorage.setItem('gp_app_version', GP_APP_VERSION);
    console.log(`[GestionPro] Version ${GP_APP_VERSION} — cache rôles vidé`);
  }
})();

let currentLang = localStorage.getItem('gp_lang') || 'fr';

var TRANSLATIONS = {
  fr: {
    // Nav
    nav_dashboard:'Tableau de bord', nav_caisse:'Caisse & Ventes',
    nav_conteneurs:'Conteneurs', nav_commandes:'Ordres (Ventes)',
    nav_docscont:'Docs Conteneurs', nav_fonds:'Fonds de caisse',
    nav_stock:'Stock', nav_locaux:'Locaux / Zones',
    nav_clients:'Clients', nav_alerts:'Alertes', nav_settings:'Paramètres',
    // Titles
    title_dashboard:'Tableau de bord', title_caisse:'Caisse & Ventes',
    title_conteneurs:'Gestion Conteneurs', title_commandes:'Ordres & Ventes',
    title_docscont:'Documents Conteneurs', title_fonds:'Fonds de Caisse',
    title_stock:'Gestion du Stock', title_locaux:'Gestion des Locaux / Zones',
    title_clients:'Gestion Clients', title_alerts:'Alertes & Notifications',
    title_settings:'Paramètres',
    title_superadmin:'👑 Super Admin — Panneau Central',
    title_employes:'👨‍💼 Gestion des Employés',
    title_conges:'🏖️ Gestion des Congés',
    title_livraisons:'🚚 Bons de Livraison',
    'title_docs-rh':'📋 Documents RH',
    'title_docs-admin':'🏢 Documents Administratifs',
    'title_owner-admin':'🏢 Mes Clients GestionPro',
    // Dashboard
    dash_sales_today:"Ventes aujourd'hui", dash_transactions:'transactions',
    dash_products_stock:'Produits en stock', dash_alerts:'alertes',
    dash_active_clients:'Clients actifs', dash_credits:'Crédits en cours',
    dash_clients_label:'clients', dash_recent_sales:'📈 Dernières ventes',
    dash_see_all:'Voir tout', dash_alerts_stock:'⚠️ Alertes stock',
    dash_no_sales:'Aucune vente enregistrée', dash_stock_ok:'Stock OK',
    dash_date:'Date', dash_client:'Client', dash_total:'Total', dash_payment:'Paiement',
    // Caisse
    search_product:'Rechercher un produit...', cart_title:'🛒 Panier',
    cart_clear:'Vider', cart_empty_hint:'Cliquez sur les produits',
    cart_empty_stock:'Ajoutez des produits au stock',
    client_passage:'Client de passage',
    tva_off:'TVA désactivée', tva_on:'TVA activée', tva_click:'Cliquer pour activer',
    subtotal:'Sous-total', tva_label:'TVA', total_label:'TOTAL',
    payment_mode:'Mode de paiement',
    pay_cash:'💵 Espèces', pay_card:'💳 Carte', pay_credit:'📋 Crédit', toast_saved:'✅ Sauvegardé',
    btn_validate_recu:'🧾 Valider + Reçu', btn_validate_facture:'📄 Valider + Facture',
    // Stock
    search_stock:'Nom, code, référence...',
    all_categories:'Toutes catégories', all_containers:'Tous conteneurs',
    all_zones:'Toutes les zones', all_statuts:'Tous statuts',
    status_ok:'🟢 OK', status_low:'🟡 Stock bas', status_out:'🔴 Rupture',
    btn_new_product:'➕ Nouveau',
    btn_csv_import:'📂 CSV', btn_csv_model:'📥 Modèle CSV',
    btn_export_json:'📤 Exporter (avec photos)', btn_import_json:'📥 Importer (avec photos)',
    stock_inventory:'📦 Inventaire produits', stock_products:'produits',
    col_photo:'Photo', col_product:'Produit / Réf.', col_category:'Catégorie',
    col_stock:'Stock', col_min:'Min.', col_price:'Prix vente',
    col_zone:'Zone', col_cost:'Prix achat', col_profit:'Bénéfice/pcs',
    col_margin:'Marge %', col_status:'Statut', col_actions:'Actions',
    no_products:'Aucun produit',
    // Locaux
    search_locals:'🔍 Rechercher dans les locaux...', btn_new_local:'🏪 Nouveau local',
    local_assigned:'Produits assignés', local_total:'total',
    local_no_zone:'⚠️ Sans zone assignée',
    local_no_zone_desc:"Ces produits n'ont pas de local défini",
    local_pieces:'pièces', local_refs:'références',
    local_buy_val:'valeur achat', local_benef:'bénéfice pot.',
    local_no_local:'Aucun local configuré',
    local_no_local_hint:'Créez des locaux et assignez vos produits via le champ "Zone"',
    local_assign:'Voir & assigner',
    local_see_stock:'📦 Voir stock',
    local_ruptures:'rupture(s)', local_bas_stock:'stock bas',
    local_form_name:'Nom du local *', local_form_desc:'Description',
    local_form_resp:'Responsable', local_form_color:'Couleur / Icône',
    local_col_product:'Produit', local_col_code:'Code', local_col_category:'Catégorie',
    local_col_stock:'Stock', local_col_price:'Prix vente', local_col_cost:'Prix achat',
    local_col_profit:'Bénéfice/pcs', local_col_status:'Statut',
    local_totals:'TOTAUX', local_benef_pot:'Bénéfice potentiel',
    local_buy_value:'Valeur achat (MAD)', local_val_vente:'Valeur vente',
    local_no_products:'Aucun produit dans ce local',
    local_no_products_hint:"Assignez des produits via Stock → champ \"Zone\"",
    local_stat_locaux:'Locaux configurés', local_stat_assigned:'Produits assignés',
    local_stat_nozone:'Sans zone assignée', local_stat_value:'Valeur totale (MAD)',
    local_see_stock_nav:'→ Voir dans Stock',
    // Clients
    search_client:'🔍 Rechercher client...', btn_new_client:'➕ Nouveau client',
    no_clients:'Aucun client enregistré',
    client_credit_used:'Crédit utilisé', client_limit:'Limite',
    client_balance:'Solde restant', client_transactions:'transactions',
    client_add_title:'👤 Nouveau client', client_edit_title:'✏️ Modifier client',
    client_name:'Nom complet *', client_phone:'Téléphone', client_city:'Ville',
    client_notes:'Notes', client_credit_limit:'Limite de crédit (MAD)',
    client_col_name:'Nom', client_col_phone:'Téléphone', client_col_city:'Ville',
    client_col_credit:'Crédit utilisé', client_col_limit:'Limite',
    client_col_balance:'Solde', client_col_actions:'Actions',
    client_no_trans:'Aucune transaction',
    // Alertes
    no_alerts:'Aucune alerte — Tout le stock est OK !',
    alert_current_stock:'Stock actuel', alert_min_req:'Minimum requis',
    alert_to_order:'À commander', alert_rupture:'🔴 Rupture totale', alert_low:'🟡 Stock bas',
    // Conteneurs
    search_cont:'🔍 Rechercher conteneur...', cont_all_statuts:'Tous les statuts',
    cont_en_cours:'En cours', cont_retard:'En retard', cont_sorti:'Sortis',
    cont_new_btn:'🚢 Nouveau conteneur', cont_new_ordre:'📑 Nouvel ordre',
    cont_stat_total:'Total', cont_stat_encours:'En cours',
    cont_stat_retard:'En retard', cont_stat_sortis:'Sortis',
    cont_col_numero:'N° Ordre', cont_col_date:'Date', cont_col_cont:'Conteneur',
    cont_col_fourn:'Fournisseur', cont_col_refs:'Références', cont_col_val:'Valeur totale',
    cont_col_statut:'Statut', cont_col_actions:'Actions',
    // Conteneur modal labels
    cont_modal_title_new:'🚢 Nouveau Conteneur',
    cont_modal_title_edit:'✏️ Modifier Conteneur',
    cont_section_general:'📋 Informations générales',
    cont_section_dims:'📦 Dimensions & Poids',
    cont_section_frais:"💰 Frais d'importation (MAD)",
    cont_section_refs:'📦 Références du conteneur',
    cont_section_repartition:'⚖️ Méthode de répartition des frais',
    cont_field_numero:'N° Conteneur *',
    cont_field_fourn:'Fournisseur',
    cont_field_pays:"Pays d'origine",
    cont_field_date_arr:"Date d'arrivée *",
    cont_field_date_lim:'Date limite sortie *',
    cont_field_statut:'Statut',
    cont_field_poids:'Poids total (kg)',
    cont_field_cbm:'Volume total (CBM)',
    cont_field_cartons:'Nombre total cartons',
    cont_field_type:'Type conteneur',
    cont_field_douane:'Frais de douane',
    cont_field_port:'Frais de port / fret',
    cont_field_transit:'Frais de transit',
    cont_field_autres:'Autres frais',
    cont_field_retard:'⚠️ Frais de retard',
    cont_retard_auto:'🤖 Automatique (par jour)',
    cont_retard_manuel:'✏️ Manuel (montant total)',
    cont_field_retard_jour:'Frais retard / jour (MAD)',
    cont_field_jours:'Jours de retard',
    cont_field_retard_total:'Montant total frais de retard (MAD)',
    cont_total_frais:'💰 Total frais :',
    cont_add_ref:'➕ Ajouter une référence',
    cont_repartition_valeur:'Proportionnel à la valeur',
    cont_repartition_poids:'Proportionnel au poids ✓',
    cont_repartition_egal:'Parts égales',
    cont_btn_apercu:'👁️ Aperçu répartition',
    cont_btn_save:'✅ Enregistrer',
    cont_btn_cancel:'Annuler',
    cont_apercu_title:'⚖️ Aperçu de la répartition des frais',
    cont_apercu_confirm:'✅ Confirmer & Enregistrer',
    cont_detail_title:'📦 Détail conteneur',
    cont_stat_label_total:'Total conteneurs',
    cont_stat_label_encours:'En cours',
    cont_stat_label_retard:'En retard',
    cont_stat_label_sortis:'Sortis',
    cont_frais_tot:'MAD frais tot.',
    cont_statut_sorti:'✅ Sorti',
    cont_statut_retard:'🔴 Retard',
    cont_statut_encours:'🟡 En cours',
    cont_refs_label:'Références',
    cont_cartons_label:'Cartons',
    cont_pcs_label:'Total pcs',
    cont_frais_label:'💰 Frais :',
    cont_limite_label:'Limite :',
    cont_jours_retard:'jours de retard — Frais estimés :',
    cont_sortie_dans:'Sortie dans',
    cont_jours:'jour(s) !',
    cont_option_en_cours:'En cours',
    cont_option_sorti:'Sorti',
    no_cont:'Aucun conteneur',
    cont_detail_arrivee:"Date d'arrivée",
    cont_detail_limite:'Date limite sortie',
    cont_add_to_stock:'📦 Intégrer au stock',
    cont_btn_edit:'✏️ Modifier',
    cont_btn_delete:'🗑️ Supprimer',
    cont_docs_title:"📑 Documents d'importation (Conteneurs)",
    cont_no_docs:'Aucun document',
    // Ordres/Commandes
    search_ord:'🔍 Client, référence...', ord_all_pay:'Tous paiements',
    ord_reset:'↺ Reset', ord_history:'📋 Historique des ordres',
    ord_col_numero:'N° Ordre', ord_col_date:'Date & Heure', ord_col_client:'Client',
    ord_col_items:'Articles', ord_col_ht:'Sous-total HT', ord_col_tva:'TVA',
    ord_col_ttc:'Total TTC', ord_col_pay:'Paiement', ord_col_actions:'Actions',
    ord_no_orders:'Aucune commande',
    // Fonds de caisse
    fonds_quick_op:'⚡ Opération rapide',
    fonds_description:'Description', fonds_amount:'Montant (MAD)',
    fonds_depot:'➕ Dépôt espèces', fonds_retrait:'💸 Retrait caisse',
    fonds_charge:'📋 Déclarer une charge',
    fonds_today:'📅 Résumé du jour', fonds_history:'📋 Historique des opérations',
    fonds_all:'Toutes', fonds_ventes:'Ventes', fonds_depots:'Dépôts',
    fonds_retraits:'Retraits', fonds_charges:'Charges',
    fonds_open:'🔓 Ouvrir caisse', fonds_close:'🔒 Clôturer le jour',
    fonds_col_date:'Date & Heure', fonds_col_type:'Type',
    fonds_col_desc:'Description', fonds_col_in:'Entrée',
    fonds_col_out:'Sortie', fonds_col_balance:'Solde',
    fonds_stat_balance:'Solde caisse', fonds_stat_sales:'Ventes du jour',
    fonds_stat_depot:'Dépôts', fonds_stat_charges:'Charges & Retraits',
    // Produit modal
    prod_add_title:'📦 Ajouter un produit', prod_photo:'Photo du produit',
    prod_click_photo:'Cliquez pour ajouter une photo', prod_change_photo:'📷 Changer',
    prod_name:'Nom du produit *', prod_category:'Catégorie',
    prod_price:'Prix de vente (MAD) *', prod_cost:"Prix d'achat (MAD)",
    prod_stock:'Stock actuel *', prod_min:'Stock minimum alerte',
    prod_unit:'Unité', prod_code:'Code produit', prod_zone:'🏪 Zone / Local de stockage',
    prod_zone_ph:'Local 1, Entrepôt A, Rayon 3...',
    prod_edit_title:'✏️ Modifier le produit',
    // Produit modal
    prod_photo_lbl:'Photo du produit',
    prod_click_photo2:'Cliquez pour ajouter une photo',
    prod_change_photo2:'📷 Changer',
    prod_click_change:'Cliquez pour changer la photo',
    prod_name_lbl:'Nom du produit *',
    prod_name_lbl_short:'Nom *',
    prod_cat_lbl:'Catégorie',
    prod_price_lbl:'Prix de vente (MAD) *',
    prod_price_lbl_short:'Prix vente (MAD) *',
    prod_cost_lbl:"Prix d'achat (MAD)",
    prod_cost_lbl_short:"Prix achat (MAD)",
    prod_stock_lbl:'Stock actuel *',
    prod_min_lbl:'Stock minimum alerte',
    prod_min_lbl_short:'Stock minimum',
    prod_unit_lbl:'Unité',
    prod_code_lbl:'Code produit',
    prod_zone_lbl:'🏪 Zone / Local de stockage',
    prod_btn_cancel:'Annuler',
    prod_btn_save:'✅ Enregistrer',
    prod_btn_update:'✅ Mettre à jour',
    prod_ph_name:'Ex: Coca-Cola 33cl',
    prod_ph_cat:'Ex: Boissons',
    prod_ph_unit:'Pièce, Kg, L...',
    prod_ph_code:'SKU / Code-barres',
    prod_ph_zone:'Local 1, Entrepôt A, Rayon 3...',
    prod_ph_zone2:'Local 1, Entrepôt A...',
    // Local modal
    local_modal_title_new:'🏪 Nouveau Local',
    local_modal_title_edit:'🏪 Modifier Local',
    local_detail_title_lbl:'🏪 Détail Local',
    local_nom_lbl:'Nom du local *',
    local_desc_lbl:'Description',
    local_resp_lbl:'Responsable',
    local_couleur_lbl:'Couleur / Icône',
    local_btn_cancel:'Annuler',
    local_btn_save:'✅ Enregistrer',
    local_btn_close:'✕ Fermer',
    local_btn_edit2:'✏️ Modifier',
    local_ph_nom:'Local 1, Entrepôt A, Rayon 3...',
    local_ph_desc:'Adresse, étage, notes...',
    local_ph_resp:'Nom du responsable',
    local_col_accent:'🟢 Vert (principal)',
    local_col_blue:'🔵 Bleu',
    local_col_orange:'🟠 Orange',
    local_col_purple:'🟣 Violet',
    local_col_red:'🔴 Rouge',
    local_col_gold:'🟡 Or',
    // Client modal
    client_nom_lbl:'Nom complet *',
    client_phone_lbl:'Téléphone',
    client_limit_lbl:'Limite de crédit (MAD)',
    client_city_lbl:'Ville',
    client_notes_lbl:'Notes',
    client_btn_cancel:'Annuler',
    client_btn_save:'✅ Enregistrer',
    client_ph_nom:'Mohammed Alami',
    client_ph_phone:'06XXXXXXXX',
    client_ph_city:'Casablanca',
    client_ph_notes:'Informations supplémentaires...',
    client_btn_close:'Fermer',
    client_btn_modify_limit:'✏️ Modifier limite',
    client_btn_pay:'💵 Enregistrer paiement',
    // Références conteneur
    ref_title:'Référence',
    ref_code:'Code réf. *',
    ref_nom:'Nom produit *',
    ref_cartons:'Nb cartons *',
    ref_pcs:'Pcs / carton *',
    ref_poids:'Poids / carton (kg)',
    ref_prix:'Prix achat / pcs (MAD)',
    ref_long:'Long. carton (cm)',
    ref_larg:'Larg. carton (cm)',
    ref_haut:'Haut. carton (cm)',
    // Settings
    settings_lang:'Langue / اللغة', settings_store:'🏪 Informations du commerce',
    settings_bank:'🏦 Coordonnées bancaires', settings_tva:'🧾 Gestion TVA / Taxes',
    settings_logo:"Logo de l'entreprise", settings_logo_hint:'PNG, JPG recommandé • Max 2MB',
    settings_store_name:'Nom du commerce *', settings_phone:'Téléphone',
    settings_address:'Adresse complète', settings_email:'Email',
    settings_website:'Site web', settings_ice:'ICE / N° Fiscal',
    settings_prefix:'Préfixe facture', settings_bank_name:'Banque',
    settings_iban:'RIB / IBAN', settings_notes:'Notes sur la facture',
    settings_tva_title:'Activer la TVA',
    settings_tva_desc:'Les prix saisis sont HT. La TVA sera calculée automatiquement.',
    settings_tva_on:'Activée', settings_tva_off:'Désactivée',
    btn_save:'✅ Enregistrer', btn_cancel:'Annuler', btn_edit:'✏️ Modifier',
    btn_delete:'🗑️ Supprimer', btn_close:'✕ Fermer', btn_print:'🖨️ Imprimer',
    btn_update:'✅ Mettre à jour', btn_choose_logo:'📂 Choisir logo',
    btn_remove_logo:'🗑️ Supprimer',
    // Toasts / messages JS
    toast_required:'Remplissez les champs obligatoires (*)',
    toast_product_added_to:'ajouté au stock',
    toast_product_updated:'mis à jour', toast_product_deleted:'Produit supprimé',
    toast_stock_insuf:'Stock insuffisant', toast_cart_empty:'Panier vide',
    toast_select_client:'Sélectionnez un client pour le crédit',
    toast_credit_exceeded:'Limite de crédit dépassée',
    toast_client_added:'Client ajouté', toast_client_updated:'Client mis à jour',
    toast_client_deleted:'Client supprimé', toast_invalid_amount:'Montant invalide',
    toast_local_saved:'enregistré', toast_local_deleted:'Local supprimé',
    toast_settings_saved:'✅ Paramètres enregistrés !',
    toast_logo_saved:'Logo enregistré !', toast_logo_too_big:'Logo trop grand (max 2MB)',
    toast_csv_downloaded:'Modèle CSV téléchargé !',
    toast_preparing_export:"⏳ Préparation de l'export...",
    toast_no_products:'Aucun produit à exporter',
    toast_export_done:'produit(s) exportés', toast_photos_with:'avec photos',
    toast_import_invalid:'❌ Fichier invalide — pas un export GestionPro',
    toast_import_done:'Import terminé', toast_import_added:'ajoutés',
    toast_import_updated:'mis à jour', toast_import_replaced:'produits importés',
    toast_json_error:'❌ Erreur lecture JSON',
    toast_cont_saved:'Conteneur enregistré', toast_cont_deleted:'Conteneur supprimé',
    toast_stock_from_cont_done:'produit(s) créés, mis à jour dans le stock',
    toast_name_required:'Nom obligatoire',
    toast_storage_full:'⚠️ Stockage presque plein — supprimez des photos',
    toast_loading_photos:'photo(s) en chargement...',
    toast_imported_with_photos:'produit(s) importé(s)',
    // Status
    stat_rupture:'Rupture', stat_bas:'Bas', stat_ok:'OK',
    stat_en_cours:'En cours', stat_en_retard:'En retard', stat_sorti:'Sorti',
    // Months
    months:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    no_cont:'Aucun conteneur',
    btn_new_client:'➕ Nouveau client',
    cont_new_ordre:'📑 Nouvel ordre',
    toast_name_required:'Nom obligatoire',
    toast_logo_too_big:'Logo trop grand (max 2MB)',
    // Misc
    vip:'VIP', of:'sur', page_label:'Page', results_label:'résultats',
  },
  ar: {
    // Nav
    nav_dashboard:'لوحة القيادة', nav_caisse:'الصندوق والمبيعات',
    nav_conteneurs:'الحاويات', nav_commandes:'الطلبات (المبيعات)',
    nav_docscont:'وثائق الحاويات', nav_fonds:'صندوق المال',
    nav_stock:'المخزون', nav_locaux:'المحلات / المناطق',
    nav_clients:'الزبائن', nav_alerts:'التنبيهات', nav_settings:'الإعدادات',
    // Titles
    title_dashboard:'لوحة القيادة', title_caisse:'الصندوق والمبيعات',
    title_conteneurs:'إدارة الحاويات', title_commandes:'الطلبات والمبيعات',
    title_docscont:'وثائق الحاويات', title_fonds:'صندوق المال',
    title_stock:'إدارة المخزون', title_locaux:'إدارة المحلات / المناطق',
    title_clients:'إدارة الزبائن', title_alerts:'التنبيهات والإشعارات',
    title_settings:'الإعدادات',
    title_superadmin:'👑 المدير العام',
    title_employes:'👨‍💼 إدارة الموظفين',
    title_conges:'🏖️ إدارة الإجازات',
    title_livraisons:'🚚 وصولات التسليم',
    'title_docs-rh':'📋 وثائق الموارد البشرية',
    'title_docs-admin':'🏢 الوثائق الإدارية',
    'title_owner-admin':'🏢 عملائي — GestionPro',
    // Dashboard
    dash_sales_today:'مبيعات اليوم', dash_transactions:'معاملات',
    dash_products_stock:'المنتجات في المخزون', dash_alerts:'تنبيهات',
    dash_active_clients:'الزبائن النشطون', dash_credits:'الديون الجارية',
    dash_clients_label:'زبائن', dash_recent_sales:'📈 آخر المبيعات',
    dash_see_all:'عرض الكل', dash_alerts_stock:'⚠️ تنبيهات المخزون',
    dash_no_sales:'لا توجد مبيعات مسجلة', dash_stock_ok:'المخزون جيد',
    dash_date:'التاريخ', dash_client:'الزبون', dash_total:'المجموع', dash_payment:'الدفع',
    // Caisse
    search_product:'البحث عن منتج...', cart_title:'🛒 السلة',
    cart_clear:'إفراغ', cart_empty_hint:'انقر على المنتجات',
    cart_empty_stock:'أضف منتجات للمخزون',
    client_passage:'زبون عابر',
    tva_off:'الضريبة معطلة', tva_on:'الضريبة مفعّلة', tva_click:'انقر للتفعيل',
    subtotal:'المجموع الجزئي', tva_label:'الضريبة', total_label:'المجموع الكلي',
    payment_mode:'طريقة الدفع',
    pay_cash:'💵 نقدًا', pay_card:'💳 بطاقة', pay_credit:'📋 دين', toast_saved:'✅ تم الحفظ',
    btn_validate_recu:'🧾 تأكيد + وصل', btn_validate_facture:'📄 تأكيد + فاتورة',
    // Stock
    search_stock:'الاسم، الكود، المرجع...',
    all_categories:'جميع الفئات', all_containers:'جميع الحاويات',
    all_zones:'جميع المناطق', all_statuts:'جميع الحالات',
    status_ok:'🟢 جيد', status_low:'🟡 مخزون منخفض', status_out:'🔴 نفاد',
    btn_new_product:'➕ منتج جديد',
    btn_csv_import:'📂 CSV', btn_csv_model:'📥 نموذج CSV',
    btn_export_json:'📤 تصدير (مع الصور)', btn_import_json:'📥 استيراد (مع الصور)',
    stock_inventory:'📦 قائمة المنتجات', stock_products:'منتجات',
    col_photo:'الصورة', col_product:'المنتج / المرجع', col_category:'الفئة',
    col_stock:'المخزون', col_min:'الحد الأدنى', col_price:'سعر البيع',
    col_zone:'المنطقة', col_cost:'سعر الشراء', col_profit:'ربح/قطعة',
    col_margin:'الهامش %', col_status:'الحالة', col_actions:'الإجراءات',
    no_products:'لا توجد منتجات',
    // Locaux
    search_locals:'🔍 البحث في المحلات...', btn_new_local:'🏪 محل جديد',
    local_assigned:'المنتجات المعيّنة', local_total:'إجمالي',
    local_no_zone:'⚠️ بدون منطقة',
    local_no_zone_desc:'هذه المنتجات ليس لها محل محدد',
    local_pieces:'قطع', local_refs:'مراجع',
    local_buy_val:'قيمة الشراء', local_benef:'ربح محتمل',
    local_no_local:'لا توجد محلات مضبوطة',
    local_no_local_hint:'أنشئ محلات وعيّن منتجاتك عبر حقل "المنطقة"',
    local_assign:'عرض وتعيين',
    local_see_stock:'📦 عرض المخزون',
    local_ruptures:'نفاد', local_bas_stock:'مخزون منخفض',
    local_form_name:'اسم المحل *', local_form_desc:'الوصف',
    local_form_resp:'المسؤول', local_form_color:'اللون / الأيقونة',
    local_col_product:'المنتج', local_col_code:'الكود', local_col_category:'الفئة',
    local_col_stock:'المخزون', local_col_price:'سعر البيع', local_col_cost:'سعر الشراء',
    local_col_profit:'ربح/قطعة', local_col_status:'الحالة',
    local_totals:'المجاميع', local_benef_pot:'الربح المحتمل',
    local_buy_value:'قيمة الشراء (درهم)', local_val_vente:'قيمة البيع',
    local_no_products:'لا توجد منتجات في هذا المحل',
    local_no_products_hint:'عيّن منتجات عبر المخزون ← حقل "المنطقة"',
    local_stat_locaux:'محلات مضبوطة', local_stat_assigned:'منتجات معيّنة',
    local_stat_nozone:'بدون منطقة', local_stat_value:'القيمة الإجمالية (درهم)',
    local_see_stock_nav:'← عرض في المخزون',
    // Clients
    search_client:'🔍 البحث عن زبون...', btn_new_client:'➕ زبون جديد',
    no_clients:'لا يوجد زبائن مسجلون',
    client_credit_used:'الدين المستخدم', client_limit:'الحد',
    client_balance:'الرصيد المتبقي', client_transactions:'معاملات',
    client_add_title:'👤 زبون جديد', client_edit_title:'✏️ تعديل الزبون',
    client_name:'الاسم الكامل *', client_phone:'الهاتف', client_city:'المدينة',
    client_notes:'ملاحظات', client_credit_limit:'حد الدين (درهم)',
    client_col_name:'الاسم', client_col_phone:'الهاتف', client_col_city:'المدينة',
    client_col_credit:'الدين المستخدم', client_col_limit:'الحد',
    client_col_balance:'الرصيد', client_col_actions:'الإجراءات',
    client_no_trans:'لا توجد معاملات',
    // Alertes
    no_alerts:'لا توجد تنبيهات — المخزون جيد !',
    alert_current_stock:'المخزون الحالي', alert_min_req:'الحد الأدنى المطلوب',
    alert_to_order:'الكمية للطلب', alert_rupture:'🔴 نفاد تام', alert_low:'🟡 مخزون منخفض',
    // Conteneurs
    search_cont:'🔍 البحث عن حاوية...', cont_all_statuts:'جميع الحالات',
    cont_en_cours:'قيد المعالجة', cont_retard:'متأخرة', cont_sorti:'خرجت',
    cont_new_btn:'🚢 حاوية جديدة', cont_new_ordre:'📑 أمر جديد',
    cont_stat_total:'المجموع', cont_stat_encours:'قيد المعالجة',
    cont_stat_retard:'متأخرة', cont_stat_sortis:'خرجت',
    cont_col_numero:'رقم الأمر', cont_col_date:'التاريخ', cont_col_cont:'الحاوية',
    cont_col_fourn:'المورد', cont_col_refs:'المراجع', cont_col_val:'القيمة الكلية',
    cont_col_statut:'الحالة', cont_col_actions:'الإجراءات',
    // Conteneur modal labels AR
    cont_modal_title_new:'🚢 حاوية جديدة',
    cont_modal_title_edit:'✏️ تعديل الحاوية',
    cont_section_general:'📋 المعلومات العامة',
    cont_section_dims:'📦 الأبعاد والوزن',
    cont_section_frais:'💰 تكاليف الاستيراد (درهم)',
    cont_section_refs:'📦 مراجع الحاوية',
    cont_section_repartition:'⚖️ طريقة توزيع التكاليف',
    cont_field_numero:'رقم الحاوية *',
    cont_field_fourn:'المورد',
    cont_field_pays:'بلد المنشأ',
    cont_field_date_arr:'تاريخ الوصول *',
    cont_field_date_lim:'تاريخ الخروج *',
    cont_field_statut:'الحالة',
    cont_field_poids:'الوزن الكلي (كغ)',
    cont_field_cbm:'الحجم الكلي (CBM)',
    cont_field_cartons:'عدد الكراتين',
    cont_field_type:'نوع الحاوية',
    cont_field_douane:'رسوم الجمارك',
    cont_field_port:'رسوم الميناء / الشحن',
    cont_field_transit:'رسوم العبور',
    cont_field_autres:'مصاريف أخرى',
    cont_field_retard:'⚠️ مصاريف التأخير',
    cont_retard_auto:'🤖 تلقائي (بالأيام)',
    cont_retard_manuel:'✏️ يدوي (المبلغ الكلي)',
    cont_field_retard_jour:'مصاريف التأخير / يوم (درهم)',
    cont_field_jours:'أيام التأخير',
    cont_field_retard_total:'المبلغ الإجمالي لمصاريف التأخير (درهم)',
    cont_total_frais:'💰 مجموع التكاليف :',
    cont_add_ref:'➕ إضافة مرجع',
    cont_repartition_valeur:'بالنسبة للقيمة',
    cont_repartition_poids:'بالنسبة للوزن ✓',
    cont_repartition_egal:'بالتساوي',
    cont_btn_apercu:'👁️ معاينة التوزيع',
    cont_btn_save:'✅ حفظ',
    cont_btn_cancel:'إلغاء',
    cont_apercu_title:'⚖️ معاينة توزيع التكاليف',
    cont_apercu_confirm:'✅ تأكيد وحفظ',
    cont_detail_title:'📦 تفاصيل الحاوية',
    cont_stat_label_total:'مجموع الحاويات',
    cont_stat_label_encours:'قيد المعالجة',
    cont_stat_label_retard:'متأخرة',
    cont_stat_label_sortis:'خرجت',
    cont_frais_tot:'درهم مصاريف',
    cont_statut_sorti:'✅ خرجت',
    cont_statut_retard:'🔴 متأخرة',
    cont_statut_encours:'🟡 قيد المعالجة',
    cont_refs_label:'المراجع',
    cont_cartons_label:'الكراتين',
    cont_pcs_label:'المجموع قطع',
    cont_frais_label:'💰 المصاريف :',
    cont_limite_label:'الحد :',
    cont_jours_retard:'يوم تأخير — المصاريف المقدرة :',
    cont_sortie_dans:'خروج خلال',
    cont_jours:'يوم !',
    cont_option_en_cours:'قيد المعالجة',
    cont_option_sorti:'خرجت',
    no_cont:'لا توجد حاويات',
    cont_detail_arrivee:'تاريخ الوصول',
    cont_detail_limite:'تاريخ الخروج',
    cont_add_to_stock:'📦 إضافة للمخزون',
    cont_btn_edit:'✏️ تعديل',
    cont_btn_delete:'🗑️ حذف',
    cont_docs_title:'📑 وثائق الاستيراد (الحاويات)',
    cont_no_docs:'لا توجد وثائق',
    // Ordres/Commandes
    search_ord:'🔍 الزبون، المرجع...', ord_all_pay:'جميع طرق الدفع',
    ord_reset:'↺ إعادة تعيين', ord_history:'📋 سجل الطلبات',
    ord_col_numero:'رقم الطلب', ord_col_date:'التاريخ والوقت', ord_col_client:'الزبون',
    ord_col_items:'المقالات', ord_col_ht:'المجموع قبل الضريبة', ord_col_tva:'الضريبة',
    ord_col_ttc:'المجموع الكلي', ord_col_pay:'الدفع', ord_col_actions:'الإجراءات',
    ord_no_orders:'لا توجد طلبات',
    // Fonds de caisse
    fonds_quick_op:'⚡ عملية سريعة',
    fonds_description:'الوصف', fonds_amount:'المبلغ (درهم)',
    fonds_depot:'➕ إيداع نقدي', fonds_retrait:'💸 سحب من الصندوق',
    fonds_charge:'📋 تسجيل مصروف',
    fonds_today:'📅 ملخص اليوم', fonds_history:'📋 سجل العمليات',
    fonds_all:'الكل', fonds_ventes:'المبيعات', fonds_depots:'الإيداعات',
    fonds_retraits:'السحوبات', fonds_charges:'المصاريف',
    fonds_open:'🔓 فتح الصندوق', fonds_close:'🔒 إغلاق اليوم',
    fonds_col_date:'التاريخ والوقت', fonds_col_type:'النوع',
    fonds_col_desc:'الوصف', fonds_col_in:'دخل',
    fonds_col_out:'خرج', fonds_col_balance:'الرصيد',
    fonds_stat_balance:'رصيد الصندوق', fonds_stat_sales:'مبيعات اليوم',
    fonds_stat_depot:'الإيداعات', fonds_stat_charges:'المصاريف والسحوبات',
    // Produit modal
    prod_add_title:'📦 إضافة منتج', prod_photo:'صورة المنتج',
    prod_click_photo:'انقر لإضافة صورة', prod_change_photo:'📷 تغيير',
    prod_name:'اسم المنتج *', prod_category:'الفئة',
    prod_price:'سعر البيع (درهم) *', prod_cost:'سعر الشراء (درهم)',
    prod_stock:'المخزون الحالي *', prod_min:'الحد الأدنى للتنبيه',
    prod_unit:'الوحدة', prod_code:'كود المنتج', prod_zone:'🏪 المنطقة / المحل',
    prod_zone_ph:'محل 1، مستودع أ، رف 3...',
    prod_edit_title:'✏️ تعديل المنتج',
    // Produit modal AR
    prod_photo_lbl:'صورة المنتج',
    prod_click_photo2:'انقر لإضافة صورة',
    prod_change_photo2:'📷 تغيير',
    prod_click_change:'انقر لتغيير الصورة',
    prod_name_lbl:'اسم المنتج *',
    prod_name_lbl_short:'الاسم *',
    prod_cat_lbl:'الفئة',
    prod_price_lbl:'سعر البيع (درهم) *',
    prod_price_lbl_short:'سعر البيع (درهم) *',
    prod_cost_lbl:'سعر الشراء (درهم)',
    prod_cost_lbl_short:'سعر الشراء (درهم)',
    prod_stock_lbl:'المخزون الحالي *',
    prod_min_lbl:'الحد الأدنى للتنبيه',
    prod_min_lbl_short:'الحد الأدنى',
    prod_unit_lbl:'الوحدة',
    prod_code_lbl:'كود المنتج',
    prod_zone_lbl:'🏪 المنطقة / المحل',
    prod_btn_cancel:'إلغاء',
    prod_btn_save:'✅ حفظ',
    prod_btn_update:'✅ تحديث',
    prod_ph_name:'مثال: كوكاكولا 33cl',
    prod_ph_cat:'مثال: مشروبات',
    prod_ph_unit:'قطعة، كغ، لتر...',
    prod_ph_code:'SKU / الباركود',
    prod_ph_zone:'محل 1، مستودع أ، رف 3...',
    prod_ph_zone2:'محل 1، مستودع أ...',
    // Local modal AR
    local_modal_title_new:'🏪 محل جديد',
    local_modal_title_edit:'🏪 تعديل المحل',
    local_detail_title_lbl:'🏪 تفاصيل المحل',
    local_nom_lbl:'اسم المحل *',
    local_desc_lbl:'الوصف',
    local_resp_lbl:'المسؤول',
    local_couleur_lbl:'اللون / الأيقونة',
    local_btn_cancel:'إلغاء',
    local_btn_save:'✅ حفظ',
    local_btn_close:'✕ إغلاق',
    local_btn_edit2:'✏️ تعديل',
    local_ph_nom:'محل 1، مستودع أ، رف 3...',
    local_ph_desc:'العنوان، الطابق، ملاحظات...',
    local_ph_resp:'اسم المسؤول',
    local_col_accent:'🟢 أخضر (رئيسي)',
    local_col_blue:'🔵 أزرق',
    local_col_orange:'🟠 برتقالي',
    local_col_purple:'🟣 بنفسجي',
    local_col_red:'🔴 أحمر',
    local_col_gold:'🟡 ذهبي',
    // Client modal AR
    client_nom_lbl:'الاسم الكامل *',
    client_phone_lbl:'الهاتف',
    client_limit_lbl:'حد الدين (درهم)',
    client_city_lbl:'المدينة',
    client_notes_lbl:'ملاحظات',
    client_btn_cancel:'إلغاء',
    client_btn_save:'✅ حفظ',
    client_ph_nom:'محمد العلمي',
    client_ph_phone:'06XXXXXXXX',
    client_ph_city:'الدار البيضاء',
    client_ph_notes:'معلومات إضافية...',
    client_btn_close:'إغلاق',
    client_btn_modify_limit:'✏️ تعديل الحد',
    client_btn_pay:'💵 تسجيل الدفع',
    // Références conteneur AR
    ref_title:'مرجع',
    ref_code:'كود المرجع *',
    ref_nom:'اسم المنتج *',
    ref_cartons:'عدد الكراتين *',
    ref_pcs:'قطعة / كرتون *',
    ref_poids:'وزن الكرتون (كغ)',
    ref_prix:'سعر الشراء / قطعة (درهم)',
    ref_long:'طول الكرتون (سم)',
    ref_larg:'عرض الكرتون (سم)',
    ref_haut:'ارتفاع الكرتون (سم)',
    // Settings
    settings_lang:'Langue / اللغة', settings_store:'🏪 معلومات المتجر',
    settings_bank:'🏦 المعلومات البنكية', settings_tva:'🧾 إدارة الضريبة (TVA)',
    settings_logo:'شعار الشركة', settings_logo_hint:'PNG, JPG مقترح • الحد الأقصى 2MB',
    settings_store_name:'اسم المتجر *', settings_phone:'الهاتف',
    settings_address:'العنوان الكامل', settings_email:'البريد الإلكتروني',
    settings_website:'الموقع الإلكتروني', settings_ice:'رقم ICE / الضريبي',
    settings_prefix:'بادئة الفاتورة', settings_bank_name:'البنك',
    settings_iban:'رقم الحساب (RIB/IBAN)', settings_notes:'ملاحظات على الفاتورة',
    settings_tva_title:'تفعيل الضريبة',
    settings_tva_desc:'الأسعار المدخلة قبل الضريبة. تُحسب تلقائيًا.',
    settings_tva_on:'مفعّل', settings_tva_off:'معطل',
    btn_save:'✅ حفظ', btn_cancel:'إلغاء', btn_edit:'✏️ تعديل',
    btn_delete:'🗑️ حذف', btn_close:'✕ إغلاق', btn_print:'🖨️ طباعة',
    btn_update:'✅ تحديث', btn_choose_logo:'📂 اختيار الشعار',
    btn_remove_logo:'🗑️ حذف',
    // Toasts / messages JS
    toast_required:'يرجى تعبئة الحقول الإلزامية (*)',
    toast_product_added_to:'تمت الإضافة للمخزون',
    toast_product_updated:'تم التحديث', toast_product_deleted:'تم حذف المنتج',
    toast_stock_insuf:'المخزون غير كافٍ', toast_cart_empty:'السلة فارغة',
    toast_select_client:'اختر زبونًا للدين',
    toast_credit_exceeded:'تم تجاوز حد الدين',
    toast_client_added:'تمت إضافة الزبون', toast_client_updated:'تم تحديث الزبون',
    toast_client_deleted:'تم حذف الزبون', toast_invalid_amount:'المبلغ غير صالح',
    toast_local_saved:'تم الحفظ', toast_local_deleted:'تم حذف المحل',
    toast_settings_saved:'✅ تم حفظ الإعدادات !',
    toast_logo_saved:'تم حفظ الشعار !', toast_logo_too_big:'الشعار كبير جدًا (الحد الأقصى 2MB)',
    toast_csv_downloaded:'تم تنزيل نموذج CSV !',
    toast_preparing_export:'⏳ جاري التحضير...',
    toast_no_products:'لا توجد منتجات للتصدير',
    toast_export_done:'منتج(ات) تم تصديرها', toast_photos_with:'مع صور',
    toast_import_invalid:'❌ ملف غير صالح — ليس تصديرًا من GestionPro',
    toast_import_done:'اكتمل الاستيراد', toast_import_added:'مضاف',
    toast_import_updated:'محدّث', toast_import_replaced:'منتج(ات) مستوردة',
    toast_json_error:'❌ خطأ في قراءة JSON',
    toast_cont_saved:'تم حفظ الحاوية', toast_cont_deleted:'تم حذف الحاوية',
    toast_stock_from_cont_done:'منتج(ات) أُنشئت وحُدِّثت في المخزون',
    toast_name_required:'الاسم إلزامي',
    toast_storage_full:'⚠️ التخزين شبه ممتلئ — احذف بعض الصور',
    toast_loading_photos:'صورة(صور) جاري التحميل...',
    toast_imported_with_photos:'منتج(ات) مستوردة',
    // Status
    stat_rupture:'نفاد', stat_bas:'منخفض', stat_ok:'جيد',
    stat_en_cours:'قيد المعالجة', stat_en_retard:'متأخر', stat_sorti:'خرج',
    // Months
    months:['يناير','فبراير','مارس','أبريل','ماي','يونيو','يوليوز','غشت','شتنبر','أكتوبر','نونبر','دجنبر'],
    // Misc
    vip:'VIP', of:'من', page_label:'صفحة', results_label:'نتائج',
  }
};
